In [28]:
#### **IMPORTANDO LIBRERIA NUMPY**
import numpy as np

In [29]:
### CREANDUN UNA LISTA ###
list_gods = [1,2,3,4,5,6,7,8,9,10]
list_gods

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [30]:
### TRANDFORMANDO LA LISTA A UNA ARRAY ###
arreglo = np.array(list_gods)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
### VERIFICAR EL TIPO DE ESTRUCTURA ###
type(arreglo)

numpy.ndarray

In [32]:
### VERIFICAR LOS TIPOS DE DATOS DEL ARREGLO ###
arreglo.dtype

dtype('int32')

In [33]:
### DEFINIENDO EL ARRAY DE INT32 A FLOAT32 ###
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [34]:
### TRANSFORMANDO LOS DATOS DE INT32 A FLOAT32 ###
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [35]:
### FUNCION SIMILAR A RANGE PERO USANDO ARREGLOS ###
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
### ARREGLO DE 2 EN 2 USANDO ARANGE ###
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

In [37]:
### FUNCIONES EN NUMPY ###
### OBTENIEDO EL PROMEDIO EL ARRAY ###

promedio = np.mean(arreglo)
promedio

5.5

In [38]:
### OBTENIENDO LA MEDIANA ###
mediana = np.median(arreglo)
mediana

5.5

In [39]:
### DESVIACION ESTANDAR DE UN ARREGLO ###
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

In [40]:
### GENERACION DE UN ARREGLO DE 5 ELEMENTOS DE PUROS CEROS ###
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

In [41]:
### GENERACION DE UN ARREGLO DE 10 ELEMENTOS DE PUROS UNOS ###
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
### TRANSFORMANDO EL ARREGLO DE UNOS DE PUNTO FLOTANTES A ENTEROS ###
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [43]:
### GENERANDO ARREGLO ALEATORIO DE 5 ELEMENTOS ###
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio

array([0.29721986, 0.08264987, 0.14584521, 0.74377482, 0.79365505])

In [44]:
### GENERANDO UNA AMTRIZ ALEATORIA DE 3X3 ###
matriz = np.random.rand(3,3)
matriz

array([[0.21199524, 0.93687108, 0.25522048],
       [0.51485503, 0.14025728, 0.23215116],
       [0.75224272, 0.87868184, 0.21459864]])

In [45]:
### GENERANDO UN ARREGLO ALEATORIO DE 10 NUMEROS ENTEROS DE 1 AL 5 ###
arreglo_aleatorio2 = np.random.randint(1,5,10)
arreglo_aleatorio2

array([4, 1, 2, 1, 1, 2, 4, 4, 2, 4])

In [47]:
### GENERANDO UNA MATRIZ ALEATORIA DE 5 ELEMENTOS ENTEROS DE 1 AL 100 ###
matriz2 = np.random.randint(1,100,(5,5))
matriz2

array([[27,  8, 88, 55, 60],
       [54, 35, 74, 32, 90],
       [26, 17, 51,  9, 18],
       [56, 19, 29, 64,  7],
       [36, 67, 51, 62, 56]])