In [3]:
import numpy as np

In [4]:
lista=list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
type(arreglo)

numpy.ndarray

In [7]:
arreglo.dtype

dtype('int32')

In [8]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [9]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

<h3 style="color:blue;"><b>Loco</b></h3>

In [10]:
matriz= np.random.rand(10,10)
matriz

array([[0.38394983, 0.83408131, 0.05917996, 0.77920182, 0.90948905,
        0.31780474, 0.40584792, 0.28492071, 0.65919752, 0.68321846],
       [0.97082402, 0.64167851, 0.80444871, 0.64376303, 0.1236374 ,
        0.90703959, 0.19327268, 0.43338977, 0.37775239, 0.48386252],
       [0.47540947, 0.49205677, 0.30343962, 0.85938606, 0.42663862,
        0.70581726, 0.48325789, 0.55996606, 0.33560395, 0.74314477],
       [0.64367421, 0.21908361, 0.33783957, 0.1978934 , 0.74164048,
        0.22325225, 0.4628343 , 0.70586186, 0.5250844 , 0.41262724],
       [0.48196858, 0.029827  , 0.5982571 , 0.26125191, 0.0685026 ,
        0.91457081, 0.39657585, 0.3141454 , 0.25042612, 0.97165182],
       [0.55229428, 0.62424545, 0.55589082, 0.99902449, 0.92680797,
        0.95791956, 0.16771935, 0.76866867, 0.82740643, 0.34304562],
       [0.03944767, 0.14340692, 0.18710923, 0.643354  , 0.74541994,
        0.18238409, 0.76312116, 0.17376105, 0.10804775, 0.27721699],
       [0.62342587, 0.79838563, 0.9062958

In [11]:
random_array=np.random.randint(1,5,10)
random_array

array([1, 1, 3, 4, 3, 2, 3, 2, 2, 4])

In [13]:
matriz2=np.random.randint(1,100,(15,15))
matriz2

array([[42, 73, 95, 49, 40, 78, 78,  2, 57, 49, 66, 93, 83, 42,  9],
       [51, 72, 51, 39, 84, 50, 92,  7,  5, 66, 30, 46, 96,  7, 75],
       [98, 50, 19, 59, 83, 26, 36, 41, 27, 45, 13,  8, 90, 71, 75],
       [31, 45, 84,  9, 81, 35,  3, 31, 14,  8, 29, 73, 10, 21, 60],
       [91, 86, 24, 69, 72, 72, 90, 20, 43, 72, 18, 14, 93, 83, 57],
       [95, 83, 31, 66, 17, 36, 34, 24, 24, 10, 83, 67, 51, 87, 39],
       [14, 10, 77, 39, 88, 93, 10, 54, 53, 89, 69,  4, 52, 83, 77],
       [50, 36, 53, 35, 90, 51, 58, 71, 40, 91, 77, 67, 75, 56, 73],
       [ 1, 65, 54, 32, 53, 11, 88, 72, 42, 84, 25, 52, 63, 46, 68],
       [48, 54, 49, 38, 75, 82, 77, 61, 30,  2, 13, 99, 86, 77, 84],
       [71, 20, 88, 94, 21,  1, 80,  6, 34, 50,  6, 89, 13, 56, 89],
       [60, 37, 35, 67, 87, 45, 76, 61, 66, 70,  1, 74, 84, 86, 43],
       [24,  1, 25, 88, 88, 91, 97, 30, 97, 48, 31, 29, 84,  1, 42],
       [54, 27, 35, 67,  1, 90, 28, 78, 43, 13, 68, 45, 74, 10, 14],
       [12, 18, 47, 14, 51, 66, 25